{"uuid": "edaba277-9915-4510-9b3c-9e019696e2d9", "children": ["70324e83-e62c-49b0-9dd2-70a8220c69e2", "01a83068-78e3-4382-a402-181838f75e2d", "dc9cffcc-74f2-4d42-89e0-6ee4f7302a89", "367a45c6-92e5-41a7-b257-28a85e50464b"], "befores": [{"name": "orm", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"ORMFixture\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.\n", "trace": "  File \"c:\\users\\user\\pycharmprojects\\python_training\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\user\\pycharmprojects\\python_training\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\user\\pycharmprojects\\python_training\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"C:\\Users\\user\\PycharmProjects\\python_training\\conftest.py\", line 61, in orm\n    dbfixture = ORMFixture(host=db_config[\"host\"], name=db_config[\"name\"], user=db_config[\"user\"], password=db_config[\"password\"])\n  File \"c:\\users\\user\\pycharmprojects\\python_training\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 978, in result\n    fail(message, pytrace=False)\n  File \"c:\\users\\user\\pycharmprojects\\python_training\\venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 128, in fail\n    raise Failed(msg=msg, pytrace=pytrace)\n"}, "start": 1571240409676, "stop": 1571240409682}], "start": 1571240409676, "stop": 1571240409714}